; PlatformIO project for BuddyBot
[env:BallBot]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
    -Ilib/M5_UNIT_8SERVO
    -Isrc

lib_deps =
    m5stack/M5Unified @ ^0.1.11
    m5stack/M5GFX @ ^0.1.11
    Wire

monitor_speed = 115200
